export enum ActivityActionsTypeEnumDto {
  MORE_INFORMATION = "MORE_INFORMATION",
  ACTIVITY_MEMBERS = "ACTIVITY_MEMBERS",
  MAP = "MAP",
  DISMISS = "DISMISS",
  INVITE = "INVITE",
  LEAVE = "LEAVE",
  JOIN = "JOIN",
  EDIT = "EDIT",
}
