export enum ActivityActionsTypeEnumDto {
  MORE_INFORMATION = 'MORE_INFORMATION',
  ACTIVITY_MEMBERS = 'ACTIVITY_MEMBERS',
  MAP = 'MAP',
  DISMISS = 'DISMISS',
  LEAVE = 'LEAVE',
  JOIN = 'JOIN',
  EDIT = 'EDIT'
}
