export enum ApplicationLocations {
  LOADING = "/loading",
  LOGIN = "/login",
  REGISTER = "/register",
  VERIFY = "/verify",
  PICK_USERNAME = "/pick-username",
  SELECT_PROFILE_PICTURE = "/select-picture",
  RESET_PASSWORD = "/reset-password",
  NEW_PASSWORD = "/new-password",
  WELCOME = "/welcome",
  PROFILE = "/profile",
  EDIT_PROFILE = "/edit-profile",
  SETTINGS = "/settings",
  BUDDIES = "/buddies",
  NOTIFICATIONS = "/notifications",
  ACTIVITIES = "/activities",
  CHOOSE_USERNAME_GOOGLE = "/choose-username",
  ACTIVITY_ID = "/activity",
  CREATE = "/create",
  SEARCH = "/search",
  MAP = "/map",
  CHAT = "/chat",
  AUTHENTICATION_METHOD = "/",
  FORGOTTEN_PASSWORD = "/forgotten-password",
}
