export enum ApplicationLocations {
  LOADING = "/loading",
  LOGIN = "/login",
  REGISTER = "/register",
  VERIFY = "/verify",
  PICK_USERNAME = "/pick-username",
  SELECT_PROFILE_PICTURE = "/select-picture",
  RESET_PASSWORD = "/reset-password",
  NEW_PASSWORD = "/new-password",
  WELCOME = "/welcome",
  PROFILE = "/profile",
  USER_PROFILE = "/profile/user",
  BUDDY_REQUEST = "/profile/request",
  BUDDY_PROFILE = "/profile/buddy",
  EDIT_PROFILE = "/edit-profile",
  //todo
  EDIT_ACTIVITY = "/edit-activity",
  SETTINGS = "/settings",
  BUDDIES = "/buddies",
  NOTIFICATIONS = "/notifications",
  ACTIVITIES = "/activities",
  CHOOSE_USERNAME_GOOGLE = "/choose-username",
  CHOOSE_LOCATION = "/choose-location",
  ACTIVITY_DETAIL = "/activity/detail",
  ACTIVITY_MEMBERS = "/activity-members",
  ACTIVITY_INVITE_MEMBERS = "/activity-invite",
  ACTIVITY_INVITE = "/activities/request",
  CREATE = "/create",
  SEARCH = "/search",
  MAP = "/map",
  CHAT = "/chat",
  AUTHENTICATION_METHOD = "/",
  FORGOTTEN_PASSWORD = "/forgotten-password",
}
