export enum ApplicationLocations {
  LOADING = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  VERIFY = '/verify',
  PICK_USERNAME = '/pick-username',
  RESET_PASSWORD = '/reset-password',
  NEW_PASSWORD = '/new-password',
  WELCOME = '/welcome',
  PROFILE = '/profile',
  SETTINGS = '/settings',
  BUDDIES = '/buddies',
  NOTIFICATIONS = '/notifications',
  ACTIVITES = '/activites',
  CREATE = '/create',
  SEARCH = '/search',
  CHAT = '/chat',
}
