export enum ApplicationLocations {
  LOADING = '/',
  LOGIN = '/login',
  LOGINREGISTER = '/loginregister',
  REGISTER = '/register',
  VERIFY = '/verify',
  PICK_USERNAME = '/pick-username',
  SELECT_PROFILE_PICTURE = '/select-picture',
  RESET_PASSWORD = '/reset-password',
  NEW_PASSWORD = '/new-password',
  WELCOME = '/welcome',
  PROFILE = '/profile',
  EDIT_PROFILE = '/edit-profile',
  SETTINGS = '/settings',
  BUDDIES = '/buddies',
  NOTIFICATIONS = '/notifications',
  ACTIVITES = '/activities',
  CREATE = '/create',
  SEARCH = '/search',
  CHAT = '/chat',
}
