name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build
        run: docker build . --tag offli/frontend:${{ github.sha }}
      - name: Docker Push
        run: docker push offli/frontend:${{ github.sha }}
