name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build
        run: docker build . --tag offli/frontend:${{ github.sha }}
      - name: Docker Push
        run: docker push offli/frontend:${{ github.sha }}
